name: Deploy Backend Services

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'chat-socket/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_BACKEND }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  deploy-chat-socket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_SOCKET }}
          api-key: ${{ secrets.RENDER_API_KEY }}